services:
  - type: web
    name: skillx
    env: python
    buildCommand: "npm install --prefix Frontend && npm run build --prefix Frontend && pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.11.0
